---
title: "Publications"
csl: apa.csl
bibliography: references.bib
---

# First author publications

-   [Effects of land use configuration, seasonality and point source on water quality in a tropical watershed: A case study of the Johor River Basin](https://www.sciencedirect.com/science/article/abs/pii/S0048969721017290)[@pak2021effects] 
- [A framework for assessing the adequacy of Water Quality Index–Quantifying parameter sensitivity and uncertainties in missing values distribution](https://www.sciencedirect.com/science/article/abs/pii/S004896972035511X)[@pak2021framework] 
- [Benchmarking of hierarchical bayesian model aggregation, xgboost and optimal band ratio analysis (OBRA) models for total suspended sediments retrieval from remote sensing](https://dr.ntu.edu.sg/handle/10356/156772)[@pak2022benchmarking] 
- [Retrieval of total suspended solids concentration from hyperspectral sensing using hierarchical Bayesian model aggregation for optimal multiple band ratio analysis](https://www.sciencedirect.com/science/article/abs/pii/S1570644322000612)[@pak2023retrieval] 
- [CoastalWQL: An Open-Source Tool for Drone-Based Mapping of Coastal Turbidity Using Push Broom Hyperspectral Imagery](https://www.mdpi.com/2072-4292/16/4/708)[@pak2024coastalwql]

# Co-authored publications

- [UAV-based remote sensing of turbidity in coastal environment for regulatory monitoring and assessment](https://www.sciencedirect.com/science/article/abs/pii/S0025326X23009165)[@kieu2023uav] 
- [A Framework for Survey Planning Using Portable Unmanned Aerial Vehicles (pUAVs) in Coastal Hydro-Environment](https://www.mdpi.com/2072-4292/14/9/2283)[@trinh2022framework] 
- [A Comparative Study of Multi-Rotor Unmanned Aerial Vehicles (UAVs) with Spectral Sensors for Real-Time Turbidity Monitoring in the Coastal Environment](https://www.mdpi.com/2504-446X/8/2/52)[@trinh2024comparative]

# Thesis

-   [Bachelor Thesis - 	Investigating factors responsible for soil pH and its spatial variation in the Nee Soon Swamp Forest](https://scholarbank.nus.edu.sg/handle/10635/144162)  [@pak2018investigating]
-   [Master Thesis - An assessment of river water quality : case study of Johor River basin, Malaysia](https://dr.ntu.edu.sg/handle/10356/145107) [@pak2020assessment]
-   [PhD Thesis - Remote sensing of coastal turbidity with unmanned aerial vehicle-borne multispectral and hyperspectral sensors in the coastal region of Singapore](https://dr.ntu.edu.sg/handle/10356/180742) [@pak2024remote]

# List of publications

::: {#refs}
:::
